### ISSUE TITLE
TPLinkSmartBulb cannot be used as a method

### ISSUE THREAD

**Issue by pekempy** [anthturner/TPLinkSmartDevices#3]
Hi,

I've added the DLL as a reference and it seems to be picking most things up ok but I've got an error that I can't use "TPLinkSmartBulb" as it's shown in the readme - see below.
Also, readme may have an error as it shows "smartBulb.PoweredOff = false; //turns off the bulb" - should that be smartBulb.PoweredOn = false; ?

![image](https://user-images.githubusercontent.com/22874875/57916050-fa7f2500-7889-11e9-87fd-ee852396cce1.png)

**Comment by TheBauwssss** [comment]
Just off the top of my head I'm pretty sure you need to use the `new` keyword.

**Comment by TheBauwssss** [comment]
![2019-05-17_15-10-48](https://user-images.githubusercontent.com/1992977/57930379-18627f00-78b6-11e9-85bf-711ac5c60cd4.gif)

Yes this appears to fix the example for me. It is probably a simple oversight or a remnant from an older architecture. I do not have the privileges required to push to this repo. If you're feeling up to it you could edit the README.md yourself and submit a pull request :)

**Comment by pekempy** [comment]
I think it might've  been a long week at work! Can't believe I missed that. thanks
Created PR https://github.com/anthturner/TPLinkSmartDevices/pull/5/files
