### ISSUE TITLE
Jvalue has no definition for Model

### ISSUE THREAD

**Issue by AndrewKlasen** [anthturner/TPLinkSmartDevices#8]
Hello, I cant operate my HS105, I get an error that:

Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: ''Newtonsoft.Json.Linq.JValue' does not contain a definition for 'model'' on line 67 of TPlinkDiscovery
![Capture](https://user-images.githubusercontent.com/31248235/87206943-b0040780-c2d8-11ea-8cd0-d1b13979551b.PNG)

**Comment by TheBauwssss** [comment]
Could you provide a full text dump for the ```sys_info``` JSON-object and/or the contents of the ```message``` variable?

**Comment by AndrewKlasen** [comment]
How would I send a text dump?

**Comment by AndrewKlasen** [comment]
Can anyone help with this?

**Comment by AndrewKlasen** [comment]
Bump! Anyone have this error before?

**Comment by ContactDev913** [comment]
> Bump! Anyone have this error before?

Fuck yes. Dude this is preventing me from finishing my project. I hope they help us soon. I hope we get help soon.

**Comment by ContactDev913** [comment]
> > Bump! Anyone have this error before?
> 
> Fuck yes. Dude this is preventing me from finishing my project. I hope they help us soon. I hope we get help soon.

Also, I am not having it in my code. I am having it on execution.

**Comment by ContactDev913** [comment]
> Bump! Anyone have this error before?

Just use this. This is based off the one your having issues with. Will fix the issues.
https://www.nuget.org/packages/tplink-smartdevices/

**Comment by anthturner** [comment]
I unfortunately no longer use this series of devices in my smart home so I don't have anything to test against. I'm happy to take a pull request, but I see the alternative library is pretty actively maintained; I'm thrilled to see someone has made good use of this as a base and has since picked this up in the meantime, though! :)

**Comment by AndrewKlasen** [comment]
> > Bump! Anyone have this error before?
> 
> Just use this. This is based off the one your having issues with. Will fix the issues.
> https://www.nuget.org/packages/tplink-smartdevices/

that new API works, thank you!
